version: '3.9'

services:
  frontend:
    build:
      context: ./sky-navigator
    ports:
      - "5000:80"

  backend:
    build:
      context: ./SkyNavigatorBackend
    ports:
      - "5001:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5432:5432"
