version: '3.8'

services:
  backend:
    build:
      context: ./SkyNavigatorBackend
    ports:
      - "5001:80"
  
  frontend:
    build:
      context: ./sky-navigator
    ports:
      - "3000:80"
    depends_on:
      - backend
